# Site
name: "G.Tiara Shin"
title: "Garyung Tiara Shin"
description: "A UX based product manager/desginer G.Tiara Shin."
logo: '/assets/images/favicon.png'
favicon: '/assets/images/favicon.png'
baseurl: 
google_analytics: 'UA-120547060-11'
disqus: 'blog'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: g.tiara.shin@gmail.com

# Authors
authors:
  Tiara:
    name: G. Tiara Shin
    display_name: Tiara
    gravatar: 98ffb5cdb7d0bf6803c9db93b5e354aa
    email: g.tiara.shin@gmail.com
    web: https://g-tiara-shin.github.io
    twitter: https://twitter.com/Tiara_Shin
    description: "Garyung is a UX based product manager. She is a genuine problem solver. This is a personal website of how she works or worked."
 
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-3676873461095690"
adsense-data-ad-slot: #"1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
